In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print("Type:", type(arr))
print("array dimensions:", arr.ndim)


[1 2 3 4 5]
Type: <class 'numpy.ndarray'>
array dimensions: 1


In [32]:
arr = np.arange(10, 51)  
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)


Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Shape: (41,)
Size: 41


In [31]:
arr = np.zeros((3, 4), dtype=int)
print("Original array:")
print(arr)
# Convert all zeros to fives
arr[:] = 5
print("zeros to fives:")
print(arr)


Original array:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
zeros to fives:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [30]:
arr = np.random.randint(1, 101, size=15)
# Print the array
print("Random array:", arr)
max_val = np.max(arr)
min_val = np.min(arr)
mean_val = np.mean(arr)

print("Maximum value:", max_val)
print("Minimum value:", min_val)
print("Mean value:", mean_val)


Random array: [14 80 44 25 54 76 26 43 67 51 99 98 28 91 47]
Maximum value: 99
Minimum value: 14
Mean value: 56.2


In [29]:
arr = np.arange(1, 21)
print("array:", arr)

# for even number
even_numbers = arr[arr % 2 == 0]
print("Even numbers:", even_numbers)
# Reverse the array using slicing
reversed_array = arr[::-1]
print("Reversed array:", reversed_array)


array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers: [ 2  4  6  8 10 12 14 16 18 20]
Reversed array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [28]:
arr = np.array([10, 20, 30, 40, 50])
# for first element
print("First element:", arr[0])
# for last element
print("Last element:", arr[-1])


First element: 10
Last element: 50


In [27]:
arr = np.arange(1, 17).reshape(4, 4)
print( arr)
print()
# Extract the first two rows and last two columns
extracted = arr[:2, -2:]
print( extracted)
print()
# Replace the diagonal elements with 0
np.fill_diagonal(arr, 0)
print( arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[3 4]
 [7 8]]

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
import numpy as np

# Create an array of 25 random integers between 1 and 100
arr = np.random.randint(1, 101, size=25)
print("Original array:\n", arr)

# Sort the array
sorted_arr = np.sort(arr)
print("\nSorted array:\n", sorted_arr)


In [ ]:
arr_36 = np.arange(1, 37)
# Reshape t
matrix = arr_36.reshape(6, 6)
print("Matrix:", matrix)

# Sum of each row
row_sums = np.sum(matrix, axis=1)
print("Sum of each row:", row_sums)

# Sum of each column
col_sums = np.sum(matrix, axis=0)
print("Sum of each column:", col_sums)
